In [52]:
import pandas as pd
import string
import numpy as np
import math

In [4]:
A = pd.read_csv('../../datasets/sample_citeseer_100k.csv')
B = pd.read_csv('../../datasets/sample_dblp_100k.csv')
l_block_attr = 'title'
r_block_attr = 'title'
ltable = A
rtable = B
lid = 'id'
rid = 'id'

In [5]:
def remove_stopwords(tokens, stopwords):
    out_tokens = []
    for token in tokens:
        if not stopwords.has_key(token):
            out_tokens.append(token)
    return out_tokens

def process_column(column, stop_words):
    column = column.str.translate(None, string.punctuation)
    column = column.str.lower()
    if stop_words:
        dict_stopwords = dict(zip(self.stop_words, [0] * len(self.stop_words)))
        partial_rm_stopwords_fn = partial(remove_stopwords,
                                          stopwords=dict_stopwords)
        column = column.str.split().map(partial_rm_stopwords_fn).str.join(' ')
    return column
def sample_ltable(ltable, lid, l_block_attr, nbins, sample_proportion, stopwords=[]):
    ltbl = ltable[[lid, l_block_attr]]
    ltbl = ltbl[~ltbl[l_block_attr].isnull()]
    #process columns
    ltbl[l_block_attr] = process_column(ltbl[l_block_attr], [])
    n = int(math.floor(sample_proportion*len(ltable)))
        
    # get the string lengths
    ltbl['str_len'] = ltbl.title.str.len()
    groups = ltbl.group_by('str_len')
    len_ids = {}
    for gid, g in groups:
        len_ids[gid] = list(g[lid].values)
    strlens = list(ltbl['str_len'].values)
    strlens += [max(strlens)+1]
    
    freq, edges = np.histogram(strlens, bins=nbins)

    
    bins = [[] for _ in range(10)]
    keys = sorted(len_ids.keys())
    positions = np.digitize(keys, edges)
    
    for i in range(len(keys)):
        k, p = keys[i], positions[i]
        bins[p-1].extend(len_ids[k])
    len_bins = [len(bins[i]) for i in range(len(bins))]

    
    weights = [len_bins[i]/float(sum(len_bins)) for i in range(len(bins))]
    numtups = [int(math.ceil(weights[i]*n)) for i in range(len(weights))]
    numtups, sum(numtups)
    sampled = []
    for i in range(len(bins)):
        nt = numtups[i]
        np.random.seed(0)
        if len(bins[i]):
            tmp = np.random.choice(bins[i], nt)
            if len(tmp):
                sampled.extend(tmp)
    ltable.set_index(lid, inplace=True, drop=False)
    return ltable.iloc[sampled]
    

    

In [6]:
import dmagellan
from dmagellan.blocker.overlap.overlapblocker import OverlapBlocker

In [7]:
ltbl = ltable[[lid, l_block_attr]]
ltbl = ltbl[~ltbl[l_block_attr].isnull()]
ltbl[l_block_attr] = process_column(ltbl[l_block_attr], [])

In [10]:
ltbl['str_len'] = ltbl.title.str.len()

In [18]:
ll = ltbl.set_index(lid, drop=False)
ltable.set_index(lid, inplace=True, drop=False)

In [19]:
ltable.loc[899015]

id                                               899015
title                                             , and
authors             Miloslav Feistauer, Gerald Warnecke
journal                                             NaN
month                                               NaN
year                                                NaN
publication_type                                    NaN
Name: 899015, dtype: object

In [13]:
groups=(ltbl.groupby('str_len'))

In [116]:
len_ids = {}
len_freq = {}
for gid, g in groups:
    len_ids[gid] = list(g[lid].values)
    len_freq[gid] = len(len_ids[gid])
    

In [101]:
strlens = list(ltbl['str_len'].values)
print(len(strlens))
strlens += [max(strlens)+1]
print(len(strlens))
freq, edges = np.histogram(strlens, bins=10)
n = int(math.floor(0.1*len(ltable)))

edges

99999
100000


array([   0. ,   61.6,  123.2,  184.8,  246.4,  308. ,  369.6,  431.2,
        492.8,  554.4,  616. ])

In [115]:
len_freq[60]

1333

In [122]:
bins[9]

[1384387, 1384387, [1384387]]

In [138]:
bins = [[] for _ in range(10)]
keys = sorted(len_ids.keys())
positions = np.digitize(keys, edges)
for i in range(len(keys)):
    k, p = keys[i], positions[i]
    bins[p-1].extend(len_ids[k])
len_bins = [len(bins[i]) for i in range(len(bins))]


In [212]:
weights = [len_bins[i]/float(sum(len_bins)) for i in range(len(bins))]
numtups = [int(math.ceil(weights[i]*n)) for i in range(len(weights))]
numtups, sum(numtups)
sampled = []
for i in range(len(bins)):
    nt = numtups[i]
    np.random.seed(0)
    if len(bins[i]):
        tmp = np.random.choice(bins[i], nt)
        if len(tmp):
            sampled.extend(tmp)
len(sampled)
sampled[1:10]

[1303682, 163380, 308019, 808346, 1726730, 1040055, 651227, 1320243, 6826]

In [165]:
prng = np.random.RandomState(1234567890)

In [179]:
np.random.seed(0)
np.random.choice([1, 4, 5, 69, 12], 3, replace=False)


array([5, 1, 4])

In [182]:
np.random.choice([1, 4, 5, 69, 12], 3, replace=False)


array([69,  4,  5])